import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { securityHeaders, privateFilePattern } from '../../scripts/security-policy.mjs';

const quote = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$')}"`;
// Regex operands are compiled as PCRE, so their $ anchors must stay unescaped.
const quoteRegex = value => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const validRoute = value => value === '/' || /^\/(?:[A-Za-z0-9_-]+\/)*[A-Za-z0-9_-]+$/.test(value);
const validOutput = value => /^(?:[A-Za-z0-9_-]+\/)*[A-Za-z0-9_-]+\.html$/.test(value);
const HEADERS_PATH = '/REPLACE_WITH_ABSOLUTE_CONFIG_DIRECTORY/nginx-security-headers.conf';
const headerInclude = `include ${quote(HEADERS_PATH)};`;

// These files are examples for an administrator to review, never activated here.
// Only canonical root-hosted builds are supported by this Nginx adapter.
export async function generateNginxHosting({ manifest, redirects = [], outputDirectory }) {
  assert(manifest && typeof outputDirectory === 'string' && outputDirectory, 'Nginx generation requires a manifest and output directory.');
  const origin = new URL(manifest.siteOrigin);
  assert(origin.protocol === 'https:' && origin.origin === manifest.siteOrigin && /^[a-z0-9.-]+$/i.test(origin.hostname), 'Nginx requires a canonical HTTPS hostname without a path.');
  assert(!origin.port || origin.port === '443', 'This Nginx example supports standard HTTPS port 443 only.');
  assert((manifest.basePath || '/') === '/', 'Nginx hosting requires a root build (basePath /).');
  const urlStyle = manifest.urlStyle || 'clean';
  assert(['clean', 'directory'].includes(urlStyle), 'Unsupported Nginx URL style.');
  assert(Array.isArray(manifest.pages) && manifest.pages.length, 'Nginx requires rendered pages.');
  const routePaths = manifest.pages.map(page => page.path);
  assert(routePaths.includes('/') && routePaths.every(validRoute) && !routePaths.includes('/404') && new Set(routePaths).size === routePaths.length, 'Invalid or duplicate Nginx page routes.');

  const pages = manifest.pages.map(page => {
    const outputFile = page.outputFile || (page.path === '/' ? 'index.html' : urlStyle === 'directory' ? `${page.path.slice(1)}/index.html` : `${page.path.slice(1)}.html`);
    assert(validOutput(outputFile), `Unsupported Nginx output file: ${outputFile}`);
    return { ...page, outputFile, canonicalPath: page.path === '/' || urlStyle === 'clean' ? page.path : `${page.path}/` };
  });
  const pageByPath = new Map(pages.map(page => [page.path, page]));
  assert(new Set(pages.map(page => page.outputFile)).size === pages.length, 'Duplicate Nginx output files.');
  const migrations = redirects.filter(rule => !rule.has);
  assert(migrations.every(rule => validRoute(rule.source) && rule.source !== '/' && !pageByPath.has(rule.source) && pageByPath.has(rule.destination) && rule.permanent === true), 'Unsupported Nginx legacy redirect.');
  assert(new Set(migrations.map(rule => rule.source)).size === migrations.length, 'Duplicate Nginx legacy redirects.');

  const headerConfiguration = [
    '# Generated shared response-header include; keep outside the public webroot.',
    '# Repeat this include inside every location that defines any add_header.',
    ...Object.entries(securityHeaders).map(([name, value]) => `add_header ${name} ${quote(value)} always;`),
    ...(manifest.indexable === false ? ['add_header X-Robots-Tag "noindex, follow" always;'] : []),
    '',
  ].join('\n');

  const guardLines = [
    '    # Only read-only requests reach this static site.',
    '    if ($request_method !~ "^(GET|HEAD)$") { return 405; }',
    '    # Shared deny policy runs before exact-route redirects or asset handling.',
    `    if ($uri ~* ${quoteRegex(privateFilePattern.source)}) { return 403; }`,
  ];
  const methodLocation = [
    '    error_page 405 = @orbit_method_not_allowed;',
    '    location @orbit_method_not_allowed {',
    `        ${headerInclude}`,
    '        add_header Allow "GET, HEAD" always;',
    '        add_header Cache-Control "no-store" always;',
    '        return 405;',
    '    }',
  ];
  const acmeLocation = [
    '    # Only existing ACME token files are served, never scripts or PATH_INFO.',
    '    location ~ "^/\\.well-known/acme-challenge/[A-Za-z0-9_-]+$" {',
    '        default_type text/plain;',
    '        try_files $uri =404;',
    '    }',
    '    location ~ "^/\\.well-known/" { return 404; }',
  ];
  const lines = [
    '# Generated by hosting/nginx/generate.mjs. EXAMPLE ONLY; not enabled automatically.',
    `# Canonical origin: ${origin.origin}; URL style: ${urlStyle}.`,
    '# Insert in the http{} context (for example sites-available), never inside another server{}.',
    '# Replace EVERY /REPLACE_* marker with a reviewed absolute path before nginx -t.',
    '# Install only the public dist contents at the webroot; do not copy the repository.',
    '# Certificate issuance, renewal, DNS and firewall rules remain the operator responsibility.',
    '# Do not merge with legacy PHP/CMS locations or trust client X-Forwarded-Proto.',
    '',
    'server {',
    '    listen 80;',
    '    listen [::]:80;',
    `    server_name ${origin.hostname};`,
    '    root "/REPLACE_WITH_ABSOLUTE_PUBLIC_DIST";',
    '    server_tokens off;',
    '    client_max_body_size 1k;',
    `    ${headerInclude}`,
    ...guardLines,
    ...methodLocation,
    ...acmeLocation,
    '    # A fixed destination prevents Host-header based redirects; query strings remain.',
    `    location / { return 308 ${origin.origin}$request_uri; }`,
    '}',
    '',
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    `    server_name ${origin.hostname};`,
    '    ssl_certificate "/REPLACE_WITH_ABSOLUTE_FULLCHAIN_PEM";',
    '    ssl_certificate_key "/REPLACE_WITH_ABSOLUTE_PRIVATE_KEY_PEM";',
    '    ssl_protocols TLSv1.2 TLSv1.3;',
    '    ssl_session_cache shared:ORBIT_TLS:10m;',
    '    ssl_session_timeout 1d;',
    '    ssl_session_tickets off;',
    '    root "/REPLACE_WITH_ABSOLUTE_PUBLIC_DIST";',
    '    # Use the MIME file shipped by your installed Nginx package.',
    '    include "/REPLACE_WITH_ABSOLUTE_NGINX_MIME_TYPES";',
    '    default_type application/octet-stream;',
    '    charset utf-8;',
    '    server_tokens off;',
    '    autoindex off;',
    '    client_max_body_size 1k;',
    `    ${headerInclude}`,
    ...guardLines,
    ...methodLocation,
    '    # Also reject noncanonical Host values if this block is chosen as a default.',
    `    if ($host != ${quote(origin.hostname)}) { return 308 ${origin.origin}$request_uri; }`,
    '    error_page 404 /404.html;',
    '    location = /404.html {',
    '        internal;',
    `        ${headerInclude}`,
    '        add_header X-Robots-Tag "noindex, follow" always;',
    '        add_header Cache-Control "no-store" always;',
    '        try_files /404.html =404;',
    '    }',
    '    location = /404 { return 404; }',
    '    location = /404/ { return 404; }',
    '',
    '    # Explicit, query-preserving legacy migrations.',
  ];
  for (const rule of migrations) {
    const destination = `${origin.origin}${pageByPath.get(rule.destination).canonicalPath}$is_args$args`;
    for (const source of [rule.source, `${rule.source}/`, `${rule.source}.html`]) {
      lines.push(`    location = ${source} { return 308 ${destination}; }`);
    }
  }
  lines.push('', '    # Only manifest-known routes can serve HTML. Missing files remain genuine 404s.');
  for (const page of pages) {
    lines.push(
      `    location = ${page.canonicalPath} {`,
      `        ${headerInclude}`,
      '        add_header Cache-Control "public, max-age=0, must-revalidate" always;',
      `        try_files /${page.outputFile} =404;`,
      '    }',
    );
    const aliases = page.path === '/' ? ['/index.html'] : urlStyle === 'clean'
      ? [`${page.path}/`, `/${page.outputFile}`]
      : [page.path, `${page.path}.html`, `/${page.outputFile}`];
    for (const alias of new Set(aliases)) {
      if (alias !== page.canonicalPath) lines.push(`    location = ${alias} { return 308 ${origin.origin}${page.canonicalPath}$is_args$args; }`);
    }
  }
  lines.push(
    '',
    ...acmeLocation,
    '    # Only content-hashed build assets are immutable. Missing files never use home HTML.',
    '    location ~ "^/assets/[^/]+-[A-Za-z0-9_-]{8,}\\.(?:js|mjs|css)$" {',
    `        ${headerInclude}`,
    '        add_header Cache-Control "public, max-age=31536000, immutable" always;',
    '        try_files $uri =404;',
    '    }',
    '    # Publish public static formats only. Private/executable patterns were denied above.',
    '    location ~* "\\.(?:css|js|mjs|json|xml|txt|svg|webp|avif|png|jpe?g|gif|ico|pdf|mp4|webm|woff2?|ttf|otf)$" {',
    `        ${headerInclude}`,
    '        add_header Cache-Control "public, max-age=0, must-revalidate" always;',
    '        try_files $uri =404;',
    '    }',
    '    # No SPA fallback, directory index fallback, FastCGI, proxy_pass or script execution.',
    '    location / { return 404; }',
    '}',
    '',
  );
  const configuration = lines.join('\n');
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(path.join(outputDirectory, 'nginx-security-headers.conf'), headerConfiguration);
  await writeFile(path.join(outputDirectory, 'nginx-site.conf.example'), configuration);
  return { files: ['nginx-site.conf.example', 'nginx-security-headers.conf'], routeCount: pages.length, redirectCount: migrations.length };
}
