"""Refresh committed responsive assets with Python 3 and Pillow (WebP support).

Run explicitly after replacing source images; npm builds use the saved assets.
Original images are preserved. No network requests or deployment are performed.
"""
import hashlib
import json
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageOps, features

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUTPUT = PUBLIC / "images" / "responsive"
SOURCES = [
    "logo.png", "images/building_facade.png", "images/water_treatment_plant.jpg",
    "images/hero-wtp-BGjLUC-Q.jpg", "images/scada-JO4jHDve.jpg",
    "images/flow-meter-DSWy7kTd.jpg", "images/pipeline-3e9YAzse.jpg",
    "images/pump-house-rehbpR99.jpg", "images/service_oht.jpg",
    "images/network-LUJb9Wxw.jpg", "images/wtp_hero.jpg",
    "images/electro-mech-BjrTidAv.jpg", "images/pump_house.jpg",
    "images/intake-well-BztrG-Xc.jpg", "images/service_wtp.jpg",
    "images/reservoir-D5_YW2_r.jpg", "images/oht-DhEXxxnQ.jpg",
    "images/valves-Cn1fyoyr.jpg", "images/service_intake.jpg",
    "images/leader_manoj.jpg", "images/leader_vijay.jpg",
    "images/design-v2/about-engineering.webp",
    "images/design-v2/about-story-water.webp",
    "images/design-v2/about-story-field.webp",
    "images/design-v2/about-story-control.webp",
    "images/design-v2/ecosystem-riverfront.webp",
    "images/design-v2/product-studio.jpg",
]


def main():
    if not features.check("webp"):
        raise RuntimeError("Pillow must have WebP support to refresh these assets.")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    images, measurements = {}, []
    for source in SOURCES:
        original = PUBLIC / source
        raw = original.read_bytes()
        with Image.open(original) as opened:
            image = ImageOps.exif_transpose(opened).convert("RGBA" if "A" in opened.getbands() else "RGB")
            width, height = image.size
            is_logo = source == "logo.png"
            candidates = [128, 256] if is_logo else [480, 768, 1024, 1440]
            maximum = min(width, 1920)
            widths = sorted({candidate for candidate in candidates if candidate < maximum} | {maximum})
            variants = []
            for target in widths:
                resized = image.resize((target, max(1, round(height * target / width))), Image.Resampling.LANCZOS)
                stream = BytesIO()
                resized.save(stream, format="WEBP", quality=84, method=6, lossless=is_logo, exact=is_logo)
                encoded = stream.getvalue()
                # Avoid a larger re-encode of an already efficiently compressed full image.
                if target == width and len(encoded) >= len(raw) and original.suffix.lower() == ".webp":
                    url, size = "/" + source, len(raw)
                else:
                    identity = hashlib.sha256(encoded).hexdigest()[:12]
                    name = f"{original.stem}-{target}-{identity}.webp"
                    (OUTPUT / name).write_bytes(encoded)
                    url, size = "/images/responsive/" + name, len(encoded)
                variants.append({"width": target, "src": url, "bytes": size})
            largest = variants[-1]
            images["/" + source] = {
                "width": width, "height": height, "src": largest["src"],
                "srcSet": ", ".join(f"{item['src']} {item['width']}w" for item in variants),
            }
            measurements.append({"source": "/" + source, "originalBytes": len(raw), "variants": variants})
    module = "// Generated by scripts/optimize-images.py. Preserve originals; refresh after replacing them.\n"
    module += "export const responsiveImages = " + json.dumps(images, ensure_ascii=False, indent=2) + ";\n"
    (ROOT / "src" / "data" / "responsiveImages.js").write_text(module, encoding="utf-8")
    report = ROOT / ".qa" / "image-optimization.json"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(measurements, indent=2), encoding="utf-8")
    print(f"Generated responsive variants for {len(images)} images; originals preserved.")
    for item in measurements:
        last = item["variants"][-1]
        print(f"{item['source']}: {item['originalBytes']:,} -> {last['bytes']:,} bytes at {last['width']}px")


if __name__ == "__main__":
    main()
